# $Rev: 167 $
# $Date: 2017-04-05 12:12:04 +0900 (Wed, 05 Apr 2017) $
# $Author: $

auth:
    plain-text: 
        default:
            user: user
            pass: password
        arbor:
            user: user
            pass: password
        samurai:
            user: user
            pass: password
        samurai-cli:
            user: user
            pass: password
        calient:
            user: user
            pass: password
        ntm:
            user: user
            pass: password
        alcatel:
            user: user
            pass: password

    public-key: # for Public Key authentication
        default:
            user: robot
            key: $HOME/.ssh/robot_id_rsa
        test:
            user: jenkins
            key:  /var/lib/jenkins/.ssh/id_rsa



    public-key: # for Public Key authentication
        default:
            user: robot
            key: $HOME/.ssh/robot_id_rsa
        test:
            user: jenkins
            key:  /var/lib/jenkins/.ssh/id_rsa


