default:
    robot-server: 127.0.0.1
    robot-password: password
    renat-master-folder: $RENAT_PATH/config
    calient-master-path: 
    ntm-master-path: 
    ixload-tmp-remote: C:/Windows/Temp
    max-retry-for-connect: 3
    interval-between-retry: 15s
    terminal-timeout: 20m
    cmd-auto-check: False
    newline: "\r"
    slack-cmd:  $RENAT_PATH/tools/slack.sh
    slack-proxy: 127.0.0.1
    log-level: TRACE
    ignore-dead-node: FALSE
    mks-console:
        width:  1024
        height: 768
    display:
        width:  1921
        height: 1080

vchannel:
    read-timeout:   180s
    read-interval:  0.3s

extra-lib:
    - Tester
    - Hypervisor 
#    - OpticalSwitch
#    - Samurai
#    - Arbor


