default:
    robot-server: 127.0.0.1
    robot-password: password
    renat-master-folder:
    calient-master-path:
    ntm-master-path:
    ixload-tmp-remote: C:/tmp
    max-retry-for-connect: 3
    interval-between-retry: 15
    terminal-timeout: 20m
    cmd-auto-check: False
    newline: "\r\n"
    slack-cmd: ${RENAT_PATH}/tools/renat_bot.sh
    slack-proxy: 127.0.0.1:8888
    log-level: TRACE
    ignore-dead-node: FALSE

extra-lib:
    # - Tester
    # - OpticalSwitch
    # - Samurai
    #- Arbor

