default:
    robot-server: 10.128.64.100
    robot-password: password
    renat-master-folder: $RENAT_PATH/config
    calient-master-path: 
    ixload-tmp-remote: C:/tmp
    max-retry-for-connect: 3
    interval-between-retry: 15
    terminal-timeout: 20m
    cmd-auto-check: False
    newline: "\r\n"
    log-level: TRACE

extra-lib:
    - Tester
#    - Arbor
#    - OpticalSwitch
#    - Samurai

