# $Rev: 167 $
# $Date: 2017-04-05 12:12:04 +0900 (Wed, 05 Apr 2017) $
# $Author: $

device:
    # Sample definition for Ixia TCL server
    ixnet01_8009:
        type: ixnet
        description: TCL server 8.01
        ip: 10.128.4.21
        port: 8009
    ixnet01_8010:
        type: ixnet
        description: TCL server 8.01
        ip: 10.128.4.21
        port: 8010
    ixnet02_8009:
        type: ixnet
        description: TCL server
        ip: 10.128.4.22
        port: 8009
    ixnet03_8009:
        type: ixnet
        description: TCL server (VM) 7.41
        ip: 10.128.4.23
        port: 8009
    ixnet03_8010:
        type: ixnet
        description: virtual Ixia app server 7.41
        ip: 10.128.4.23
        port: 8010
    ixnet04_8009:
        type: ixnet
        description: virtual Ixia app server
        ip: 10.128.4.20
        port: 8009
    ixnet03_8014:
        type: ixnet
        description: virtual Ixia app server 7.41
        ip: 10.128.4.23
        port: 8014
    ixnet04_8010:
        type: ixnet
        description: virtual Ixia app server
        ip: 10.128.4.20
        port: 8010
    ixnet05_8009:
        type: ixnet
        description: TCL on WinXP
        ip: 10.128.8.41
        port: 8009
    ixnet03:
        type: ixnet
        description: virtual Ixia app server
        ip: 10.128.4.23
    ixnet-4-22_8013:
        type: ixnet
        description: virtual Ixia app server
        ip: 10.128.4.22
        port: 8013
    ixnet-4-23_8010:
        type: ixnet
        description: virtual Ixia app server
        ip: 10.128.4.23
        port: 8010
    ixnet-4-23_8011:
        type: ixnet
        description: virtual Ixia app server
        ip: 10.128.4.23
        port: 8011
    ixnet-4-23_8012:
        type: ixnet
        description: virtual Ixia app server
        ip: 10.128.4.23
        port: 8012
    ixload01:
        type: ixload
        description: IxLoad client
        ip: 10.128.4.20
    ixbps01:
        type: ixbps
        description: Breaking point
        ip: 10.128.4.45
    # BB naming rule - Routers
    mx480-51:
        type: juniper
        description: mx480-51
        ip: 10.128.30.51
    mx480-52:
        type: juniper
        description: mx480-52
        ip: 10.128.30.52
    mx480-53:
        type: juniper
        description: mx480-53
        ip: 10.128.30.53
    mx480-54:
        type: juniper
        description: mx480-54
        ip: 10.128.30.54
    mx480-21:
        type: juniper
        description: mx480-21
        ip: 10.128.30.21
    mx2020-25:
        type: juniper
        description: mx2020-25
        ip: 10.128.30.25
    mx2020-26:
        type: juniper
        description: mx2020-26
        ip: 10.128.30.26
    # Sample definition for routers
    mx480-10-79:
        type: juniper
        description: mx480-10-79
        ip: 10.128.10.79
    t320-10-80:
        type: juniper
        description: t320-10-80
        ip: 10.128.10.80
    mx240-31-22:
        type: juniper
        description: mx240-31-22
        ip: 10.128.31.22
    mx480-31-23:
        type: juniper
        description: mx480-31-23
        ip: 10.128.31.23
    mx480-31-24:
        type: juniper
        description: mx480-31-24
        ip: 10.128.31.24
    mx480-31-25:
        type: juniper
        description: mx480-31-25
        ip: 10.128.31.25
    # Sample definition for servers
    apollo:
        type: ssh-host
        description: main server
        ip: 10.128.3.101
    artermis:
        type: ssh-host
        description: second server
        ip: 10.128.3.102
    # Sample definition for VMX
    vmx11:
        type: juniper
        description: vmx11
        ip: 10.128.64.11
    vmx12:
        type: juniper
        description: vmx12
        ip: 10.128.64.12
    vmx13:
        type: juniper
        description: vmx13
        ip: 10.128.64.13
    vmx14:
        type: juniper
        description: vmx14
        ip: 10.128.64.14
    # Sample definition for Telecent NTM
    g4ntm-4-64:
        type: g4ntm
        description: robot patch
        ip: 10.128.4.64
        port: 9888
    # Sample definition for Calient Optical Switch
    calient01:
        type: calient
        description: 10G optical switch
        ip: 10.128.30.76
    calient-4-60:
        type: calient
        description: 10G optical switch aisle capping
        ip: 10.128.4.60
    calient-4-61:
        type: calient
        description: 100G optical switch aisle capping
        ip: 10.128.4.61
    calient-4-62:
        type: calient
        description: 10G/100G optical switch old Flets
        ip: 10.128.4.62
    # Sample definition for Arbor WebUI
    arbor-sp-ax:
        type: arbor-sp
        description: Arbor SP (A)
        ip: 91.1.255.100
    arbor-sp-a:
        type: arbor-sp
        description: Arbor SP (A)
        ip: 91.1.255.1
    arbor-sp-b:
        type: arbor-sp
        description: Arbor SP (B)
        ip: 91.1.255.2
    arbor-vsp-a:
        type: arbor-sp
        description: Arbor-vSP-A
        ip: 91.128.1.101
    arbor-vsp-b:
        type: arbor-sp
        description: Arbor-vSP-B
        ip: 91.128.1.102
    # Sample definition for Arbor CLI
    arbor-sp-cli-a:
        type: arbor-sp-cli
        description: Arbor SP (A)
        ip: 91.1.255.1
    arbor-sp-cli-b:
        type: arbor-sp-clicli-
        description: Arbor SP (B)
        ip: 91.1.255.2
    arbor-vsp-cli-a:
        type: arbor-sp
        description: Arbor-vSP-A
        ip: 91.128.1.101
    arbor-vsp-cli-b:
        type: arbor-spcli-
        description: Arbor-vSP-B
        ip: 91.128.1.102
    arbor-tms-cli-a:
        type: arbor-tms-cli
        description: Arbor TMS (A)
        ip: 91.1.30.2
    arbor-tms-cli-b:
        type: arbor-tms-cli
        description: Arbor TMS (B)
        ip: 91.1.40.2
    # Sample definition for Samurai application
    samurai14-a:
        type: samurai
        description: Samurai A
        ip: 203.105.73.234
    samurai14-b:
        type: samurai
        description: Samurai B
        ip: 91.128.1.238
    samurai16-1:
        type: samurai
        description: Samurai 16PC
        ip: 91.128.1.13
    # Sample definition for console Server
    smartcs-3-201:
        type: smartcs
        description: console server
        ip: 10.128.3.201
    smartcs-3-202:
        type: smartcs
        description: console server
        ip: 10.128.3.202
    smartcs-3-203:
        type: smartcs
        description: console server
        ip: 10.128.3.203
    # Sample definition for Alcatel
    alcatel-18-35:
        type: alcatel
        description: 7750 SR-7
        ip: 10.128.18.35
    # Sample definition for Cisco IOS
    cisco-18-12:
        type: cisco_asr
        description: Cisco ASR
        ip: 10.128.18.12

    
