# $Rev: 167 $
# $Date: 2017-04-05 12:12:04 +0900 (Wed, 05 Apr 2017) $
# $Author: $

access-template:
    ssh-host:
        access: ssh
        auth: public-key
        profile: default
        prompt: "@.*(>|\\$)"
        init: 
            - unalias -a
    juniper:
        access: telnet
        auth: plain-text 
        profile: default
        prompt: "@.*(#|>) " 
        init: 
            - set cli idle-timeout 0 
            - set cli screen-length 0
    cisco:
        access: ssh
        auth: plain-text
        profile: default
        prompt: "@.*(#|>) "
        init:
            - set terminal length 0
    cisco_asr:
        access: telnet
        auth: plain-text
        profile: default
        prompt: "CPU.*(#|>)" 
        login_prompt: "Username:"
        password_prompt: "Password:"
        init:
            - terminal length 0 
    gr:
        access: telnet
        auth: plain-text
        profile: flets
        prompt: ".*(#|>) " 
        init: 
            - set terminal pager disable
    alcatel:
        access: telnet
        auth: plain-text
        profile: default 
        prompt: ":.*(#|>) " 
        login_prompt: "Login:"
        password_prompt: "Password:"
        init:
            - environment no more
    samurai:
        access: webapp
        auth: plain-text
        profile: samurai
    samurai-cli:
        access: ssh
        auth: plain-text
        profile: samurai-cli
        prompt: "@.*(#)"
        init: 
            - unalias -a
    arbor-sp:
        access: webapp
        auth: plain-text
        profile: arbor
    arbor-tms:
        access: webapp
        auth: plain-text
        profile: arbor
    smartcs:
        access: telnet
        auth: plain-text
        profile: default
        prompt: ".*(#|>) "
        init:
    apresia-l2:
        access: telnet
        auth: plain-text
        profile: ap-sw
        prompt: ".*(#|>) "
        login_prompt:
        password_prompt: "login:"
        init:
            - "\n"
    yamaha-l2:
        access: telnet
        auth: plain-text
        profile: ymh
        prompt: ".*(#|>) "
        login_prompt:
        password_prompt: "Password:"
        init:
    arbor-sp-cli:
        access: ssh
        proxy_cmd: "/usr/bin/ssh -l robot -i ~/.ssh/robot_id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p 10.128.3.101"
        auth: plain-text
        profile: arbor
        prompt: "(:.*#|DIAG>) "
        init:
    arbor-tms-cli:
        access: ssh
        proxy_cmd: "/usr/bin/ssh -l robot -i ~/.ssh/robot_id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p 10.128.3.101"
        auth: plain-text
        profile: arbor
        prompt: ":.*# "
        init:
    sandvine-spb:
        access: ssh
        auth: plain-text
        profile: sandvine-spb
        prompt: ".*(#|>) "
        init:
            -   svcli
    sandvine-sde:
        access: ssh
        auth: plain-text
        profile: sandvine-sde
        prompt: ".*(#|>) "
        init:
            -   svcli
    sandvine-pts:
        access: ssh
        auth: plain-text
        profile: sandvine-pts
        prompt: ".*($|>) "
        init:
            -   svcli
    telnet-host:
        access: telnet
        auth: plain-text
        profile: default
        prompt: ".*(#|$)"

snmp-template:
